# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\EX1GuessNum2\ui\guess_num.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\code\\python project\\pyqt5\\EX1GuessNum2\\ui\\../../favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.guessButton = QtWidgets.QPushButton(Form)
        self.guessButton.setGeometry(QtCore.QRect(140, 180, 75, 23))
        self.guessButton.setObjectName("guessButton")
        self.numShow = QtWidgets.QLineEdit(Form)
        self.numShow.setGeometry(QtCore.QRect(100, 100, 151, 41))
        self.numShow.setObjectName("numShow")

        self.retranslateUi(Form)
        self.guessButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Guess Number"))
        self.guessButton.setToolTip(_translate("Form", "GUESS NUMBER"))
        self.guessButton.setText(_translate("Form", "Guess Me"))
        self.numShow.setText(_translate("Form", "Please input number"))
