# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\EX1GuessNum2\ui\guess_num_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 314)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.guessButton = QtWidgets.QPushButton(self.centralwidget)
        self.guessButton.setGeometry(QtCore.QRect(160, 160, 75, 23))
        self.guessButton.setObjectName("guessButton")
        self.numShow = QtWidgets.QLineEdit(self.centralwidget)
        self.numShow.setGeometry(QtCore.QRect(120, 80, 151, 41))
        self.numShow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.numShow.setObjectName("numShow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.guessButton.setToolTip(_translate("MainWindow", "GUESS NUMBER"))
        self.guessButton.setText(_translate("MainWindow", "Guess Me"))
        self.numShow.setToolTip(_translate("MainWindow", "GUESS DONE"))
        self.numShow.setText(_translate("MainWindow", "Please input number"))
