# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\EX1GuessNum\ui\guess_num_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.guessButton = QtWidgets.QPushButton(Dialog)
        self.guessButton.setGeometry(QtCore.QRect(130, 170, 75, 23))
        self.guessButton.setObjectName("guessButton")
        self.numShow = QtWidgets.QLineEdit(Dialog)
        self.numShow.setGeometry(QtCore.QRect(110, 100, 113, 31))
        self.numShow.setText("")
        self.numShow.setObjectName("numShow")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GUESS NUM"))
        self.guessButton.setText(_translate("Dialog", "Button"))
        self.numShow.setToolTip(_translate("Dialog", "Please input num"))
        self.exitButton.setText(_translate("Dialog", "exit"))
