'''
Author: your name
Date: 2022-04-23 17:14:10
LastEditTime: 2022-05-05 23:06:38
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: \pyqt5\vrf\vrf_define.py
'''

import sys
sys.path.append("..")


BIT0 = 1 << 0
BIT1 = 1 << 1
BIT2 = 1 << 2
BIT3 = 1 << 3
BIT4 = 1 << 4
BIT5 = 1 << 5
BIT6 = 1 << 6
BIT7 = 1 << 7

# ------ dict key number, do not repeat
DATA_SA = 0
DATA_DA = 1
DATA_CC = 2
DATA_BC = 3
DATA_EA = 4
DATA_CMD = 5

RCCONTROL_ADDR = 20
MAIN_ADDR = 21
DATA_LEN = 22
# DATA_CMD = 3
CMD_REPLAY = 24
SYSTEM_MODE = 25
CMD_TYPE = 26
WIND_SPEED = 27
WIN_DIR_UP = 28
WIN_DIR_LR = 29
SYS_TEMPT = 30
MAIN_ADDR_H = 31
MAIN_ADDR_L = 32
SYSTEM_NUMBBER = 33
INDOOR_NUMBER = 34
CMD_FORMATE = 35
ERROR_SYSTEM_NUM = 36
ERROR_INDOOR_NUM = 37
ERROR_CODE = 38
MYPRINT_FUNCTION = 39   # use for test print
UD_WINDIR_GROUP = 40
ALLOW_MODE = 41
SPEED_GROUP = 42
COLD_TEMP_PERIOD = 43
WARM_TEMP_PERIOD = 44
WET_TEMP_PERIOD = 45
AUTO_TEMP_PERIOD = 46
LR_WINDIR_GROUP = 47
PRE_HEAT = 48
NANOE_AB = 49
NANOEG_AB = 50
SYSTEM_STATUS = 51
PRE_INDOOR = 52         #INDOOR FIRST
FRESH_AIR = 53
MODE_FIT = 54
# ALLOW_AUTO = 55
TRY_RUN = 56
FILTER_RST_SIGN = 57
CENTRAL_CTR_BAN_FLAG = 58
CENTRAL_CTR_ADDR = 59
STYLE_A2W_TEMPT = 60        #
WARNING_MACHINE = 61
SAVE_ENERGY = 62
ECONAVI = 63
NANOE_STATUS = 64
CLEANING = 65
SYSTEM_TEMP_GROUP = 66
SYSTEM_SPEED_GROUP = 67
TIMER_TYPE = 68
TIMER_HOUR = 69
TIMER_REMAIN_HOUR = 70
EP_ADDR = 71



# end ----------

DATA_STATIC_DICT={
    RCCONTROL_ADDR : 'RCCONTROL_ADDR',
    MAIN_ADDR : 'MAIN_ADDR',
    DATA_LEN : 'DATA_LEN',
    DATA_CMD : 'DATA_CMD',
    CMD_REPLAY : 'CMD_REPLAY',
    SYSTEM_MODE : 'SYSTEM_MODE',
    CMD_TYPE : 'CMD_TYPE',
    WIND_SPEED : 'WIND_SPEED',
    WIN_DIR_UP : 'WIN_DIR_UP',
    WIN_DIR_LR : 'WIN_DIR_LR',
    SYS_TEMPT : 'SYS_TEMPT',
    MAIN_ADDR_H: 'MAIN_ADDR_H',
    MAIN_ADDR_L : 'MAIN_ADDR_L',
    SYSTEM_NUMBBER : 'SYSTEM_NUMBBER',
    INDOOR_NUMBER : 'INDOOR_NUMBER',
    CMD_FORMATE : 'CC CMD FORMAT' ,
    
}

# --------------------------
CMD_CC_MASK_RESPONSE = BIT0
CMD_CC_MASK_HAVE_SA = BIT1
CMD_CC_MASK_CMD_FORMAT = BIT2|BIT3
CMD_CC_MASK_HAVE_SUB = BIT4
CMD_CC_MASK_CMD_SYSTEM = BIT5|BIT6

CMD_CC_CMD_FORMAT_CONFIG = 0
CMD_CC_CMD_FORMAT_REQUEST = BIT2
CMD_CC_CMD_FORMAT_RESPONSE = BIT3
CMD_CC_CMD_FORMAT_CHANGE = BIT2|BIT3

CMD_CC_TYPE_BIT0_DICT ={
    0 : 'CC NOT NEED RESPONSE',
    1 : 'CC NEED RESPONSE'
}

CMD_CC_TYPE_BIT3_4_DICT ={
    0x00 << 2 : 'CC 00 CONFIG',
    0x01 << 2 : 'CC 01 REQUEST CMD',
    0x02 << 2 : 'CC 02 RESPONSE CMD',
    0x03 << 2 : 'CC 03 STATE CHANGE CMD'
}

CMD_CC_TYPE_BIT5_6_DICT ={
    0x00 << 5 : 'CC EX DEFALULT',
    0x01 << 5 : 'CC EX TEMPT GET ADDR',
    0x02 << 5 : 'CC EX RESPONSE FE',
    0x03 << 5 : 'CC EX KEEP'
}

# -------------------

SYSTEM_MODE_DICT = {
    1 : 'SYSTEM_MODE_WARM',
    2 : 'SYSTEM_MODE_COLD',
    3 : 'SYSTEM_MODE_WIND',
    4 : 'SYSTEM_MODE_WET',
    5 : 'SYSTEM_MODE_AUTO_WARM',
    6 : 'SYSTEM_MODE_AUTO_COLD',
}

CMD4C_TYPE_DIC ={
    BIT3 : 'CMD_TYPE_4C_TEMPE',
    BIT4 : 'CMD_TYPE_4C_WINDSPEED',
    BIT5 : 'CMD_TYPE_4C_UP_WIND_DIR',
    BIT6|BIT7 : 'CMD_TYPE_4C_LR_WIND_DIR',
    BIT6|BIT7|BIT5 :  'CMD_TYPE_4C_UP_LR_WIND_DIR'
}

WIND_SPEED_DIC = {
    2 : 'WIND_SPEED_AUTO',
    3 : 'WIND_SPEED_LEVEL5',
    4 : 'WIND_SPEED_LEVEL3',
    5 : 'WIND_SPEED_LEVEL1',
    BIT6 + 4 : 'WIND_SPEED_LEVEL4',
    BIT6 + 5 : 'WIND_SPEED_LEVEL2',
    BIT7 :  'WIND_SPEED_SPEC_STRONG',  # SELF DEFINE BIT
    BIT5 :  'WIND_SPEED_SPEC_MUTE', # SELF DEFINE BIT
}

WIN_DIR_UP_DIC = {
    7<<3 : 'WIND_DIR_UD_AUTO_STOP',
    2<<3 : 'WIND_DIR_UD_LEVEL1',
    3<<3 : 'WIND_DIR_UD_LEVEL2',
    4<<3 : 'WIND_DIR_UD_LEVEL3',
    5<<3 : 'WIND_DIR_UD_LEVEL4',
    6<<3 : 'WIND_DIR_UD_LEVEL5',
    1<<3 : 'WIND_DIR_UD_AUTO'
}

WIN_DIR_LR_DIC = {
    0 : 'WIND_DIR_LR_AUTO_STOP',
    7+ (7<<3) : 'WIND_DIR_LR_AUTO_STOP',
    2+ (2<<3) : 'WIND_DIR_LR_LEVEL1',
    3+ (3<<3) : 'WIND_DIR_LR_LEVEL2',
    4+ (7<<3) : 'WIND_DIR_LR_LEVEL3',
    5+ (5<<3) : 'WIND_DIR_LR_LEVEL4',
    6+ (6<<3) : 'WIND_DIR_LR_LEVEL5',
    1+ (1<<3) : 'WIND_DIR_LR_AUTO'
}


DATA_AU0 = 6
DATA_AU1 = 7
DATA_AN = 8
DATA_CA = 9
CMD49RES_DIC = {
    1 : 1
}

# CMD_FORMAT_SETTING = 0
# CMD_FORMAT_REQUEST = 1
# CMD_FORMAT_REPLY = 2
# CMD_FORMAT_STATUS_CHANGE = 3

# ERROR_SYSTEM_NUM = 0
# ERROR_INDOOR_NUM = 1
# ERROR_CODE = 2

ERRCODE_DIC = {
    ERROR_SYSTEM_NUM : 'ErrorSystemNum',
    ERROR_INDOOR_NUM : 'ErrorIndoorNum',
    ERROR_CODE : 'ErrorCode'
}


PRINT_FUNCTION_DIC={
    CMD_CC_CMD_FORMAT_CONFIG : 'myprint_cmd0x{}_request',
    CMD_CC_CMD_FORMAT_REQUEST : 'myprint_cmd0x{}_request',
    CMD_CC_CMD_FORMAT_RESPONSE : 'myprint_cmd0x{}_response',
    CMD_CC_CMD_FORMAT_CHANGE : 'myprint_cmd0x{}_response'
}


# 0a res data
CMD0A_RES_DATA_FL = 6
CMD0A_RES_DATA_RS = 7
CMD0A_RES_DATA_FM = 8
CMD0A_RES_DATA_CT = 9
CMD0A_RES_DATA_CB = 10
CMD0A_RES_DATA_HT = 11
CMD0A_RES_DATA_HB = 12
CMD0A_RES_DATA_DT = 13
CMD0A_RES_DATA_DB = 14
CMD0A_RES_DATA_FT = 15
CMD0A_RES_DATA_FB = 16
CMD0A_RES_DATA_FL2 = 17

# WIN DIR
UD_WIND_DIR_GROUP_NO = 0 #					// 娌℃湁涓婁笅椋庡悜   
UD_WIND_DIR_GROUP_3 = 1 #					// 涓婁笅椋庡悜3妗�      
UD_WIND_DIR_GROUP_5 = 2 #					// 涓婁笅椋庡悜5妗�  
UD_WIND_DIR_GROUP_ONLY_AUTO = 3 #			// 涓婁笅椋庡悜鍙湁鑷姩  
UD_WIND_DIR_GROUP_DICT = {
    UD_WIND_DIR_GROUP_NO : 'UD_WIND_DIR_GROUP_NO',
    UD_WIND_DIR_GROUP_3 : 'UD_WIND_DIR_GROUP_3',
    UD_WIND_DIR_GROUP_5 : 'UD_WIND_DIR_GROUP_5',
    UD_WIND_DIR_GROUP_ONLY_AUTO : 'UD_WIND_DIR_GROUP_ONLY_AUTO',
}

LR_WIND_DIR_GROUP_NO = 0 #					// 娌℃湁宸﹀彸椋庡悜   
LR_WIND_DIR_GROUP_3 = 1 #					// 宸﹀彸椋庡悜3妗�    
LR_WIND_DIR_GROUP_5 = 2 #					// 宸﹀彸椋庡悜5妗�   
LR_WIND_DIR_GROUP_ONLY_AUTO = 3 #			// 宸﹀彸椋庡悜鍙湁鑷姩   
LR_WIND_DIR_GROUP_DICT = {
    LR_WIND_DIR_GROUP_NO : 'LR_WIND_DIR_GROUP_NO',
    LR_WIND_DIR_GROUP_3 : 'LR_WIND_DIR_GROUP_3',
    LR_WIND_DIR_GROUP_5 : 'LR_WIND_DIR_GROUP_5',
    LR_WIND_DIR_GROUP_ONLY_AUTO : 'LR_WIND_DIR_GROUP_ONLY_AUTO',
}

SYSTEM_MODE_AUTO = 0
SYSTEM_MODE_WARM = 1
SYSTEM_MODE_COLD = 2
SYSTEM_MODE_WET = 3
SYSTEM_MODE_WIND = 4
SYSTEM_MODE_GROUP_DICT = {
    SYSTEM_MODE_AUTO : 'SYSTEM_MODE_AUTO',
    SYSTEM_MODE_WARM : 'SYSTEM_MODE_WARM',
    SYSTEM_MODE_COLD : 'SYSTEM_MODE_COLD',
    SYSTEM_MODE_WET : 'SYSTEM_MODE_WET',
    SYSTEM_MODE_WIND : 'SYSTEM_MODE_WIND',
}

WIND_SPEED_GROUP_NO = 0
WIND_SPEED_GROUP_3 = 1
WIND_SPEED_GROUP_5 = 2
WIND_SPEED_GROUP_DICT = {
    WIND_SPEED_GROUP_NO : 'WIND_SPEED_GROUP_NO',
    WIND_SPEED_GROUP_3 : 'WIND_SPEED_GROUP_3',
    WIND_SPEED_GROUP_5 : 'WIND_SPEED_GROUP_5'
}


# cmd 81 main response 
CMD81_RES_DATA_D0 = 6
CMD81_RES_DATA_D1 = 7
CMD81_RES_DATA_D2 = 8
CMD81_RES_DATA_D3 = 9
CMD81_RES_DATA_D4 = 10
CMD81_RES_DATA_D5 = 11
CMD81_RES_DATA_D6 = 12
CMD81_RES_DATA_D7 = 13
CMD81_RES_DATA_D8 = 14
CMD81_RES_DATA_D9 = 15
CMD81_RES_DATA_D10 = 16
CMD81_RES_DATA_D11= 17
CMD81_RES_DATA_D12 = 18
CMD81_RES_DATA_D13 = 19

CMD81_RES_WIN_DIR_UP_DIC = {
    7 : 'WIND_DIR_UD_AUTO_STOP',
    2 : 'WIND_DIR_UD_LEVEL1',
    3 : 'WIND_DIR_UD_LEVEL2',
    4 : 'WIND_DIR_UD_LEVEL3',
    5 : 'WIND_DIR_UD_LEVEL4',
    6 : 'WIND_DIR_UD_LEVEL5',
    1 : 'WIND_DIR_UD_AUTO'
}

CMD0F_RES_DATA_FET_1 = 6
CMD0F_RES_DATA_FET_2 = 7
CMD0F_RES_DATA_FET_3 = 8
CMD0F_RES_DATA_FET_4 = 9
CMD0F_RES_DATA_FT_1 = 10
CMD0F_RES_DATA_FT_2 = 11
CMD0F_RES_DATA_FT_3 = 12
CMD0F_RES_DATA_FT_EX = 13

TIMER_TYPE_NO_SET = 0
TIMER_TYPE_ONCE_OFF = 5
TIMER_TYPE_CYCLE_OFF = 6
TIMER_TYPE_ONCE_ON = 7
TIMER_TYPE_DICT = {
    TIMER_TYPE_NO_SET : 'TIMER_TYPE_NO_SET',
    TIMER_TYPE_ONCE_OFF : 'TIMER_TYPE_ONCE_OFF',
    TIMER_TYPE_CYCLE_OFF : 'TIMER_TYPE_CYCLE_OFF',
    TIMER_TYPE_ONCE_ON : 'TIMER_TYPE_ONCE_ON',
}
