'''
Author: your name
Date: 2022-04-23 17:14:10
LastEditTime: 2022-04-23 17:14:11
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: \pyqt5\vrf\vrf_define.py
'''
BIT0 = 1 << 0
BIT1 = 1 << 1
BIT2 = 1 << 2
BIT3 = 1 << 3
BIT4 = 1 << 4
BIT5 = 1 << 5
BIT6 = 1 << 6
BIT7 = 1 << 7

DATA_SA = 0
DATA_DA = 1
DATA_CC = 2
DATA_BC = 3
DATA_EA = 4
DATA_CMD = 5

RCCONTROL_ADDR = 20
MAIN_ADDR = 21
DATA_LEN = 22
# DATA_CMD = 3
CMD_REPLAY = 24
SYSTEM_MODE = 25
CMD_TYPE = 26
WIND_SPEED = 27
WIN_DIR_UP = 28
WIN_DIR_LR = 29
SYS_TEMPT = 30
MAIN_ADDR_H = 31
MAIN_ADDR_L = 32
SYSTEM_NUMBBER = 33
INDOOR_NUMBER = 34
CMD_FORMATE = 35
ERROR_SYSTEM_NUM = 36
ERROR_INDOOR_NUM = 37
ERROR_CODE = 38


DATA_STATIC_DICT={
    RCCONTROL_ADDR : 'RCCONTROL_ADDR',
    MAIN_ADDR : 'MAIN_ADDR',
    DATA_LEN : 'DATA_LEN',
    DATA_CMD : 'DATA_CMD',
    CMD_REPLAY : 'CMD_REPLAY',
    SYSTEM_MODE : 'SYSTEM_MODE',
    CMD_TYPE : 'CMD_TYPE',
    WIND_SPEED : 'WIND_SPEED',
    WIN_DIR_UP : 'WIN_DIR_UP',
    WIN_DIR_LR : 'WIN_DIR_LR',
    SYS_TEMPT : 'SYS_TEMPT',
    MAIN_ADDR_H: 'MAIN_ADDR_H',
    MAIN_ADDR_L : 'MAIN_ADDR_L',
    SYSTEM_NUMBBER : 'SYSTEM_NUMBBER',
    INDOOR_NUMBER : 'INDOOR_NUMBER',
    CMD_FORMATE : 'CC CMD FORMAT' ,
    
}

# --------------------------
CMD_CC_MASK_RESPONSE = BIT0
CMD_CC_MASK_HAVE_SA = BIT1
CMD_CC_MASK_CMD_FORMAT = BIT2|BIT3
CMD_CC_MASK_HAVE_SUB = BIT4
CMD_CC_MASK_CMD_SYSTEM = BIT5|BIT6

CMD_CC_CMD_FORMAT_CONFIG = 0
CMD_CC_CMD_FORMAT_REQUEST = BIT2
CMD_CC_CMD_FORMAT_RESPONSE = BIT3

CMD_CC_TYPE_BIT0_DICT ={
    0 : 'CC NOT NEED RESPONSE',
    1 : 'CC NEED RESPONSE'
}

CMD_CC_TYPE_BIT3_4_DICT ={
    0x00 << 2 : 'CC 00 CONFIG',
    0x01 << 2 : 'CC 01 REQUEST CMD',
    0x02 << 2 : 'CC 02 RESPONSE CMD',
    0x03 << 2 : 'CC 03 STATE CHANGE CMD'
}

CMD_CC_TYPE_BIT5_6_DICT ={
    0x00 << 5 : 'CC EX DEFALULT',
    0x01 << 5 : 'CC EX TEMPT GET ADDR',
    0x02 << 5 : 'CC EX RESPONSE FE',
    0x03 << 5 : 'CC EX KEEP'
}

# -------------------

SYSTEM_MODE_DICT = {
    1 : 'SYSTEM_MODE_WARM',
    2 : 'SYSTEM_MODE_COLD',
    3 : 'SYSTEM_MODE_WIND',
    4 : 'SYSTEM_MODE_WET',
    5 : 'SYSTEM_MODE_AUTO_WARM',
    6 : 'SYSTEM_MODE_AUTO_COLD',
}

CMD4C_TYPE_DIC ={
    BIT3 : 'CMD_TYPE_4C_TEMPE',
    BIT4 : 'CMD_TYPE_4C_WINDSPEED',
    BIT5 : 'CMD_TYPE_4C_UP_WIND_DIR',
    BIT6|BIT7 : 'CMD_TYPE_4C_LR_WIND_DIR',
    BIT6|BIT7|BIT5 :  'CMD_TYPE_4C_UP_LR_WIND_DIR'
}

WIND_SPEED_DIC = {
    2 : 'WIND_SPEED_AUTO',
    3 : 'WIND_SPEED_LEVEL5',
    4 : 'WIND_SPEED_LEVEL3',
    5 : 'WIND_SPEED_LEVEL1',
    BIT6 + 4 : 'WIND_SPEED_LEVEL4',
    BIT6 + 5 : 'WIND_SPEED_LEVEL2',
}

WIN_DIR_UP_DIC = {
    7<<3 : 'WIND_DIR_UD_AUTO_STOP',
    2<<3 : 'WIND_DIR_UD_LEVEL1',
    3<<3 : 'WIND_DIR_UD_LEVEL2',
    4<<3 : 'WIND_DIR_UD_LEVEL3',
    5<<3 : 'WIND_DIR_UD_LEVEL4',
    6<<3 : 'WIND_DIR_UD_LEVEL5',
    1<<3 : 'WIND_DIR_UD_AUTO'
}

WIN_DIR_LR_DIC = {
    7+ (7<<3) : 'WIND_DIR_LR_AUTO_STOP',
    2+ (2<<3) : 'WIND_DIR_LR_LEVEL1',
    3+ (3<<3) : 'WIND_DIR_LR_LEVEL2',
    4+ (7<<3) : 'WIND_DIR_LR_LEVEL3',
    5+ (5<<3) : 'WIND_DIR_LR_LEVEL4',
    6+ (6<<3) : 'WIND_DIR_LR_LEVEL5',
    1+ (1<<3) : 'WIND_DIR_LR_AUTO'
}


DATA_AU0 = 6
DATA_AU1 = 7
DATA_AN = 8
DATA_CA = 9
CMD49RES_DIC = {
    1 : 1
}

# CMD_FORMAT_SETTING = 0
# CMD_FORMAT_REQUEST = 1
# CMD_FORMAT_REPLY = 2
# CMD_FORMAT_STATUS_CHANGE = 3

# ERROR_SYSTEM_NUM = 0
# ERROR_INDOOR_NUM = 1
# ERROR_CODE = 2

ERRCODE_DIC = {
    ERROR_SYSTEM_NUM : 'ErrorSystemNum',
    ERROR_INDOOR_NUM : 'ErrorIndoorNum',
    ERROR_CODE : 'ErrorCode'
}
