# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\EX_SINGNAL\ui\signal5_mulwindow_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDisplay.setGeometry(QtCore.QRect(100, 50, 261, 41))
        self.textDisplay.setObjectName("textDisplay")
        self.pushButton_new = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new.setGeometry(QtCore.QRect(90, 160, 75, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.pushButton_signal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_signal.setGeometry(QtCore.QRect(190, 160, 75, 23))
        self.pushButton_signal.setObjectName("pushButton_signal")
        self.pushButton_attr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_attr.setGeometry(QtCore.QRect(290, 160, 75, 23))
        self.pushButton_attr.setObjectName("pushButton_attr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_new.setText(_translate("MainWindow", "pbNew"))
        self.pushButton_signal.setText(_translate("MainWindow", "pbAttr"))
        self.pushButton_attr.setText(_translate("MainWindow", "pbSig"))
