# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\EX_SINGNAL\ui\signal3_1_signal_emit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_noParam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_noParam.setGeometry(QtCore.QRect(50, 30, 101, 23))
        self.pushButton_noParam.setObjectName("pushButton_noParam")
        self.pushButton_int = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_int.setGeometry(QtCore.QRect(50, 60, 75, 23))
        self.pushButton_int.setObjectName("pushButton_int")
        self.pushButton_str = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_str.setGeometry(QtCore.QRect(50, 90, 75, 23))
        self.pushButton_str.setObjectName("pushButton_str")
        self.pushButton_list = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_list.setGeometry(QtCore.QRect(50, 120, 75, 23))
        self.pushButton_list.setObjectName("pushButton_list")
        self.pushButton_dict = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dict.setGeometry(QtCore.QRect(50, 150, 75, 23))
        self.pushButton_dict.setObjectName("pushButton_dict")
        self.pushButton_strNotInt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_strNotInt.setGeometry(QtCore.QRect(50, 190, 121, 23))
        self.pushButton_strNotInt.setObjectName("pushButton_strNotInt")
        self.pushButton_intNotStr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_intNotStr.setGeometry(QtCore.QRect(50, 220, 121, 23))
        self.pushButton_intNotStr.setObjectName("pushButton_intNotStr")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(350, 90, 91, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 140, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_noParam.setText(_translate("MainWindow", "sig_no_param"))
        self.pushButton_int.setText(_translate("MainWindow", "sig_int"))
        self.pushButton_str.setText(_translate("MainWindow", "sig_int_str"))
        self.pushButton_list.setText(_translate("MainWindow", "sig_list"))
        self.pushButton_dict.setText(_translate("MainWindow", "sig_dict"))
        self.pushButton_strNotInt.setText(_translate("MainWindow", "sig_str_not_int"))
        self.pushButton_intNotStr.setText(_translate("MainWindow", "sit_int_not_str"))
        self.pushButton_1.setText(_translate("MainWindow", "PushButton_1"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButto_2n"))
