# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\hello\ui\hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\code\\python project\\pyqt5\\hello\\ui\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lcdDisp = QtWidgets.QLCDNumber(Dialog)
        self.lcdDisp.setGeometry(QtCore.QRect(20, 60, 331, 61))
        self.lcdDisp.setObjectName("lcdDisp")
        self.lcdSlide = QtWidgets.QSlider(Dialog)
        self.lcdSlide.setGeometry(QtCore.QRect(20, 170, 320, 20))
        self.lcdSlide.setProperty("value", 0)
        self.lcdSlide.setOrientation(QtCore.Qt.Horizontal)
        self.lcdSlide.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.lcdSlide.setObjectName("lcdSlide")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(110, 230, 75, 23))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Dialog)
        self.lcdSlide.valueChanged['int'].connect(self.lcdDisp.display)
        self.exitButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hello"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
