# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python project\pyqt5\vrf\ui\ui_boundrate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(288, 224)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 50, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 19, 146, 152))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.comboBox_cc = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_cc.setObjectName("comboBox_cc")
        self.gridLayout.addWidget(self.comboBox_cc, 4, 1, 1, 1)
        self.comboBox_stopbit = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_stopbit.setObjectName("comboBox_stopbit")
        self.gridLayout.addWidget(self.comboBox_stopbit, 3, 1, 1, 1)
        self.comboBox_boundrate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_boundrate.setObjectName("comboBox_boundrate")
        self.gridLayout.addWidget(self.comboBox_boundrate, 1, 1, 1, 1)
        self.comboBox_bits = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_bits.setObjectName("comboBox_bits")
        self.gridLayout.addWidget(self.comboBox_bits, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox_flow = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_flow.setObjectName("comboBox_flow")
        self.gridLayout.addWidget(self.comboBox_flow, 8, 1, 1, 1)
        self.comboBox_serialList = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_serialList.setObjectName("comboBox_serialList")
        self.gridLayout.addWidget(self.comboBox_serialList, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "flow"))
        self.label_2.setText(_translate("Dialog", "bit"))
        self.label_4.setText(_translate("Dialog", "cc"))
        self.label_3.setText(_translate("Dialog", "Stopbit"))
        self.label.setText(_translate("Dialog", "Boundrate"))
        self.pushButton.setText(_translate("Dialog", "OK"))
